In [1]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.
null_vector = np.zeros(10)
null_vector[4] = 1

# 2. Create a vector with values ranging from 10 to 49.
vector_range_10_to_49 = np.arange(10, 50)

# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()

# 6. Create a random vector of size 30 and find the mean value.
random_vector = np.random.rand(30)
mean_value = random_vector.mean()

# Print the results for each problem
print("1. Null Vector with 1 at the fifth position:")
print(null_vector)
print("\n2. Vector with values ranging from 10 to 49:")
print(vector_range_10_to_49)
print("\n3. 3x3 Matrix with values ranging from 0 to 8:")
print(matrix_3x3)
print("\n4. Indices of non-zero elements in [1,2,0,0,4,0]:")
print(non_zero_indices)
print("\n5. Minimum value:", min_value)
print("   Maximum value:", max_value)
print("\n6. Mean value of a random vector of size 30:", mean_value)


1. Null Vector with 1 at the fifth position:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

2. Vector with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3. 3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

4. Indices of non-zero elements in [1,2,0,0,4,0]:
(array([0, 1, 4], dtype=int64),)

5. Minimum value: 0.0028539543232551923
   Maximum value: 0.99696234095145

6. Mean value of a random vector of size 30: 0.48652110306460955
